services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    environment:
        POSTGRES_DB: 'pulse_flow'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
    container_name: pgdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

