services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: 'pulse_flow'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  postgres-data:
