services:
  django:
    build: .
    container_name: django
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py PulseFlow.wsgi:application"
    restart: always
    expose:
      - "8000"
    volumes:
      - .:/app
      - /var/www/static/:/var/www/static/
      - /var/certbot/conf:/etc/letsencrypt/:ro
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    environment:
      POSTGRES_DB: 'pulse_flow'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    container_name: pgdb
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/static/:/var/www/static/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - django
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/certbot/conf:/etc/letsencrypt/:rw
      - /var/certbot/www/:/var/www/certbot/:rw
    depends_on:
      - nginx
volumes:
  postgres-data:

