services:
  django:
    build: ./backend
    container_name: django
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py PulseFlow.wsgi:application"
    restart: always
    expose:
      - "8000"
    volumes:
      - ./backend:/app
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    environment:
      POSTGRES_DB: 'pulse_flow'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    container_name: pgdb
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - django

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - django
      - frontend
volumes:
  postgres-data:
