services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    environment:
        POSTGRES_DB: 'pulse_flow'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
    container_name: pgdb
    ports:
      - "5439:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

