# Generated by Django 5.0.4 on 2024-05-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_identifier', models.CharField(max_length=100, unique=True)),
                ('website_link', models.URLField(null=True)),
                ('company_type', models.CharField(choices=[('IT', 'Information Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing')], max_length=100)),
                ('logo', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(null=True)),
                ('income', models.FloatField(null=True)),
                ('files', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_project_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', 'Company Creator'), ('BACK', 'Backend Developer')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('description', models.TextField(max_length=1000, null=True)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(null=True)),
                ('actual_end_date', models.DateField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.project')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pulse.taskstate')),
            ],
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOUR', 'Hour rate')], max_length=100, null=True)),
                ('rate', models.FloatField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.task')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.project')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pulse.taskstate')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.user')),
            ],
        ),
    ]
