# Generated by Django 5.0.4 on 2024-05-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstates',
            old_name='priority',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
